import type { Metadata } from 'next'
import '../styles/globals.css'
import '@mantine/core/styles.css'
import { MantineProvider } from '@mantine/core'
import theme from '@/styles/mantine'
import { ReactNode } from 'react'

const TITLE = 'ToDoToDo'
export const metadata: Metadata = {
  title: 'ToDoToDo',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode
}>) {
  // 서버에서 초기 컬러 스킴을 결정(쿠키 등). 없으면 light.
  // const initial = (cookies()?.get('theme')?.value as 'light' | 'dark') ?? 'light'
  return (
    <html lang="en">
      {/*<body suppressHydrationWarning>*/}
      <body>
        <MantineProvider theme={theme}>{children}</MantineProvider>
      </body>
    </html>
  )
}
